export const strings = {
    about_serverVersion: "Server Version: ",
    about_serverAPI: "Server API: ",
    KITSU: "Kitsu",
    TMDB: "TMDB",
    API_ERROR: "Error fetching API data.",
    TRENDING_ERROR: "Error loading trending content.",
    SEARCH_ERROR: "Error loading search results.",
    CONTENT_ERROR: "Error loading content.",
    LIST_ERROR: "Error loading list.",
    PROFILE_ERROR: "Error loading profile.",
    SEARCH_NO_RESULTS: "No results found.",
    SEARCH_RESULTS: "Search Results",
    trending: "Trending",
    anime: "anime",
    movie: "movie",
    tv: "tv",
    movie_year: "primary_release_year",
    tv_year: "first_air_date_year",
    TMDB_poster_url: "https://image.tmdb.org/t/p/w500",
    email_in_use: "Email already in use.",
    registration_error: "Error registering user.",
    password_mismatch: "Passwords do not match.",
};